/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CropService } from "../crop.service";
import { CropCreateInput } from "./CropCreateInput";
import { Crop } from "./Crop";
import { CropFindManyArgs } from "./CropFindManyArgs";
import { CropWhereUniqueInput } from "./CropWhereUniqueInput";
import { CropUpdateInput } from "./CropUpdateInput";
import { LiveUpdateFindManyArgs } from "../../liveUpdate/base/LiveUpdateFindManyArgs";
import { LiveUpdate } from "../../liveUpdate/base/LiveUpdate";
import { LiveUpdateWhereUniqueInput } from "../../liveUpdate/base/LiveUpdateWhereUniqueInput";
import { PriceHistoryFindManyArgs } from "../../priceHistory/base/PriceHistoryFindManyArgs";
import { PriceHistory } from "../../priceHistory/base/PriceHistory";
import { PriceHistoryWhereUniqueInput } from "../../priceHistory/base/PriceHistoryWhereUniqueInput";

export class CropControllerBase {
  constructor(protected readonly service: CropService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Crop })
  async createCrop(@common.Body() data: CropCreateInput): Promise<Crop> {
    return await this.service.createCrop({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        season: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Crop] })
  @ApiNestedQuery(CropFindManyArgs)
  async crops(@common.Req() request: Request): Promise<Crop[]> {
    const args = plainToClass(CropFindManyArgs, request.query);
    return this.service.crops({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        season: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Crop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async crop(
    @common.Param() params: CropWhereUniqueInput
  ): Promise<Crop | null> {
    const result = await this.service.crop({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        season: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Crop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCrop(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() data: CropUpdateInput
  ): Promise<Crop | null> {
    try {
      return await this.service.updateCrop({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          season: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Crop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCrop(
    @common.Param() params: CropWhereUniqueInput
  ): Promise<Crop | null> {
    try {
      return await this.service.deleteCrop({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          season: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/liveUpdates")
  @ApiNestedQuery(LiveUpdateFindManyArgs)
  async findLiveUpdates(
    @common.Req() request: Request,
    @common.Param() params: CropWhereUniqueInput
  ): Promise<LiveUpdate[]> {
    const query = plainToClass(LiveUpdateFindManyArgs, request.query);
    const results = await this.service.findLiveUpdates(params.id, {
      ...query,
      select: {
        createdAt: true,

        crop: {
          select: {
            id: true,
          },
        },

        id: true,

        market: {
          select: {
            id: true,
          },
        },

        time: true,
        updateMessage: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/liveUpdates")
  async connectLiveUpdates(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() body: LiveUpdateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      liveUpdates: {
        connect: body,
      },
    };
    await this.service.updateCrop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/liveUpdates")
  async updateLiveUpdates(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() body: LiveUpdateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      liveUpdates: {
        set: body,
      },
    };
    await this.service.updateCrop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/liveUpdates")
  async disconnectLiveUpdates(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() body: LiveUpdateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      liveUpdates: {
        disconnect: body,
      },
    };
    await this.service.updateCrop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/priceHistories")
  @ApiNestedQuery(PriceHistoryFindManyArgs)
  async findPriceHistories(
    @common.Req() request: Request,
    @common.Param() params: CropWhereUniqueInput
  ): Promise<PriceHistory[]> {
    const query = plainToClass(PriceHistoryFindManyArgs, request.query);
    const results = await this.service.findPriceHistories(params.id, {
      ...query,
      select: {
        createdAt: true,

        crop: {
          select: {
            id: true,
          },
        },

        date: true,
        id: true,

        market: {
          select: {
            id: true,
          },
        },

        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/priceHistories")
  async connectPriceHistories(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() body: PriceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      priceHistories: {
        connect: body,
      },
    };
    await this.service.updateCrop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/priceHistories")
  async updatePriceHistories(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() body: PriceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      priceHistories: {
        set: body,
      },
    };
    await this.service.updateCrop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/priceHistories")
  async disconnectPriceHistories(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() body: PriceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      priceHistories: {
        disconnect: body,
      },
    };
    await this.service.updateCrop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/fetch-agmarknet-prices")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async FetchAgmarknetPrices(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.FetchAgmarknetPrices(body);
  }
}
