/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Market } from "./Market";
import { MarketCountArgs } from "./MarketCountArgs";
import { MarketFindManyArgs } from "./MarketFindManyArgs";
import { MarketFindUniqueArgs } from "./MarketFindUniqueArgs";
import { CreateMarketArgs } from "./CreateMarketArgs";
import { UpdateMarketArgs } from "./UpdateMarketArgs";
import { DeleteMarketArgs } from "./DeleteMarketArgs";
import { LiveUpdateFindManyArgs } from "../../liveUpdate/base/LiveUpdateFindManyArgs";
import { LiveUpdate } from "../../liveUpdate/base/LiveUpdate";
import { PriceHistoryFindManyArgs } from "../../priceHistory/base/PriceHistoryFindManyArgs";
import { PriceHistory } from "../../priceHistory/base/PriceHistory";
import { MarketService } from "../market.service";
@graphql.Resolver(() => Market)
export class MarketResolverBase {
  constructor(protected readonly service: MarketService) {}

  async _marketsMeta(
    @graphql.Args() args: MarketCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Market])
  async markets(@graphql.Args() args: MarketFindManyArgs): Promise<Market[]> {
    return this.service.markets(args);
  }

  @graphql.Query(() => Market, { nullable: true })
  async market(
    @graphql.Args() args: MarketFindUniqueArgs
  ): Promise<Market | null> {
    const result = await this.service.market(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Market)
  async createMarket(@graphql.Args() args: CreateMarketArgs): Promise<Market> {
    return await this.service.createMarket({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Market)
  async updateMarket(
    @graphql.Args() args: UpdateMarketArgs
  ): Promise<Market | null> {
    try {
      return await this.service.updateMarket({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Market)
  async deleteMarket(
    @graphql.Args() args: DeleteMarketArgs
  ): Promise<Market | null> {
    try {
      return await this.service.deleteMarket(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [LiveUpdate], { name: "liveUpdates" })
  async findLiveUpdates(
    @graphql.Parent() parent: Market,
    @graphql.Args() args: LiveUpdateFindManyArgs
  ): Promise<LiveUpdate[]> {
    const results = await this.service.findLiveUpdates(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [PriceHistory], { name: "priceHistories" })
  async findPriceHistories(
    @graphql.Parent() parent: Market,
    @graphql.Args() args: PriceHistoryFindManyArgs
  ): Promise<PriceHistory[]> {
    const results = await this.service.findPriceHistories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
